# Generated by Django 2.2 on 2020-09-04 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='app51data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Releasetime', models.CharField(max_length=20)),
                ('job_name', models.CharField(max_length=50)),
                ('salary', models.CharField(max_length=20)),
                ('site', models.CharField(max_length=50)),
                ('education', models.CharField(max_length=20)),
                ('company_name', models.CharField(max_length=50)),
                ('Workexperience', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'jobsql51',
            },
        ),
    ]
